# Site settings
title:          C.J
description:    "Hi. "
baseurl:        "/"
url:            "https://asd2569484392.github.io/chaojie.github.io"

remote_theme: chesterhow/tale


# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         chaojie
  url:          https://asd2569484392.github.io/chaojie.github.io
  email:        18805698598@163.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

plugins:
  - jekyll-paginate
  - jekyll-remote-theme

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale
